# Generated by Django 4.2.5 on 2023-09-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreTimezone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "timezone_str",
                    models.CharField(default="America/Chicago", max_length=255),
                ),
            ],
            options={
                "verbose_name_plural": "Store Timezone",
            },
        ),
    ]
