# Generated by Django 4.2.5 on 2023-09-19 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "day_of_the_week",
                    models.CharField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        default=0,
                        max_length=11,
                    ),
                ),
                (
                    "start_time_local",
                    models.TimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
                (
                    "end_time_local",
                    models.TimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Business Hours",
            },
        ),
    ]
