# Generated by Django 4.2.5 on 2023-09-19 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_businesshours"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="inactive",
                        max_length=11,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Store Activity",
            },
        ),
    ]
