# Generated by Django 4.2.5 on 2023-09-20 11:18

import backend.models.report_file
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_storeactivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "verbose_name_plural": "Reports Logs",
            },
        ),
        migrations.CreateModel(
            name="ReportGeneration",
            fields=[
                (
                    "id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="backend.reportlog",
                    ),
                ),
                (
                    "report_file",
                    models.FileField(upload_to=backend.models.report_file.upload_path),
                ),
            ],
            options={
                "verbose_name_plural": "Report Files",
            },
        ),
    ]
